// Generated by CoffeeScript 1.6.3
(function() {
  var TTT;

  TTT = angular.module('TTT', ['ngRoute', 'firebase']);

  TTT.config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/', {
        templateUrl: 'partials/splash.html',
        controller: 'BoardController'
      }).when('/start', {
        templateUrl: 'partials/game-board.html',
        controller: 'BoardController'
      }).otherwise({
        redirectTo: '/'
      });
    }
  ]);

  TTT.controller('BoardController', [
    '$scope', '$firebase', function($scope, $firebase) {
      var O, X, gameRef, getMark, isBoardFull, isWon;
      O = 'o';
      X = 'x';
      $scope.O = O;
      $scope.X = X;
      gameRef = new Firebase("https://ttt-leo-tumwattana.firebaseIO.com/game");
      $scope.setupGame = function() {
        $scope.game = {};
        $scope.game.board = {
          0: '',
          1: '',
          2: '',
          3: '',
          4: '',
          5: '',
          6: '',
          7: '',
          8: ''
        };
        $scope.game.counter = 0;
        $scope.game.gameOver = false;
        return $scope.game.gameOverMessage = "";
      };
      $scope.setupGame();
      $firebase(gameRef).$bind($scope, 'game');
      $scope.resetBoard = function() {
        return $scope.setupGame();
      };
      $scope.getSplashBoard = function() {
        return $scope.game.board = [O, O, X, O, X, "", X, "", O];
      };
      $scope.placePiece = function(pos) {
        if ($scope.game.board[pos] === '') {
          $scope.game.board[pos] = getMark();
          $scope.game.counter += 1;
          if (isWon() || isBoardFull()) {
            if (isWon()) {
              $scope.game.counter -= 1;
              $scope.game.gameOverMessage = getMark().toUpperCase() + " WON!";
            } else {
              $scope.game.gameOverMessage = "It's a tie!";
            }
            return $scope.game.gameOver = true;
          }
        } else {
          return console.log("Position taken!");
        }
      };
      getMark = function(offset) {
        offset || (offset = 0);
        if (($scope.game.counter + offset) % 2 === 0) {
          return O;
        } else {
          return X;
        }
      };
      $scope.getMark = getMark;
      isWon = function() {
        var a, b, c, checkSets, set, win, _i, _len;
        checkSets = [[0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 3, 6], [1, 4, 7], [2, 5, 8], [0, 4, 8], [2, 4, 6]];
        win = false;
        for (_i = 0, _len = checkSets.length; _i < _len; _i++) {
          set = checkSets[_i];
          a = $scope.game.board[set[0]];
          b = $scope.game.board[set[1]];
          c = $scope.game.board[set[2]];
          if (a !== '' && a === b && b === c) {
            win = true;
          }
        }
        return win;
      };
      return isBoardFull = function() {
        return $scope.game.counter === 9;
      };
    }
  ]);

}).call(this);

/*
//@ sourceMappingURL=controllers.map
*/
