// Generated by CoffeeScript 1.6.3
(function() {
  var TTT;

  TTT = angular.module('TTT', ['ngRoute']);

  TTT.config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/', {
        templateUrl: 'partials/splash.html',
        controller: 'BoardController'
      }).when('/start', {
        templateUrl: 'partials/game-board.html',
        controller: 'BoardController'
      }).otherwise({
        redirectTo: '/'
      });
    }
  ]);

  TTT.controller('BoardController', [
    '$scope', function($scope) {
      var O, X, init, isBoardFull, isWon, swapTurn;
      O = 'o';
      X = 'x';
      $scope.O = O;
      $scope.X = X;
      $scope.board = [];
      $scope.fade = [];
      init = function() {
        $scope.turn = O;
        $scope.gameOver = false;
        return $scope.gameOverMessage = "";
      };
      init();
      $scope.resetBoard = function() {
        $scope.board = [];
        $scope.fade = [];
        return $scope.gameOver = false;
      };
      $scope.getSplashBoard = function() {
        return $scope.board = [O, O, X, O, X, "", X, "", O];
      };
      $scope.placePiece = function(pos) {
        if ($scope.board[pos] === void 0) {
          $scope.board[pos] = $scope.turn;
          if (isWon() || isBoardFull()) {
            if (isWon()) {
              $scope.gameOverMessage = $scope.turn.toUpperCase() + " WON!";
            } else {
              $scope.gameOverMessage = "It's a tie!";
            }
            return $scope.gameOver = true;
          } else {
            return swapTurn();
          }
        } else {
          return console.log("Position taken!");
        }
      };
      swapTurn = function() {
        return $scope.turn = $scope.turn === O ? X : O;
      };
      isWon = function() {
        var a, b, c, checkSets, set, win, _i, _len;
        checkSets = [[0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 3, 6], [1, 4, 7], [2, 5, 8], [0, 4, 8], [2, 4, 6]];
        win = false;
        for (_i = 0, _len = checkSets.length; _i < _len; _i++) {
          set = checkSets[_i];
          console.log(set);
          a = $scope.board[set[0]];
          b = $scope.board[set[1]];
          c = $scope.board[set[2]];
          if (a !== void 0 && a === b && b === c) {
            win = true;
          }
        }
        return win;
      };
      return isBoardFull = function() {
        return $scope.board.filter(function(value) {
          return value !== void 0;
        }).length === 9;
      };
    }
  ]);

}).call(this);

/*
//@ sourceMappingURL=controllers.map
*/
